## cran pkgs ===================================================================
`%nin%` <- Negate(`%in%`)
update.packages(ask = F)

install.packages("CausalImpact")
install.packages("XML")
install.packages("boot")
install.packages("cvTools")
install.packages("e1071")
install.packages("foreach")
install.packages("glmnet")
install.packages("microbenchmark")
install.packages("opencpu")
install.packages("pbapply")
install.packages("randomForest")
install.packages("rjags")
install.packages("tidycensus")
install.packages("zoo")

## other pkgs ==================================================================
install.packages("xgboost", 
                 repos=c("http://dmlc.ml/drat/",  getOption("repos")), 
                 type="source")

# needs rstan first
if("rstan" %nin% rownames(installed.packages())) { 
  source("install_rstan.R") 
}
install.packages("prophet")

# remove current version first
remove.packages("data.table")
install.packages("data.table", type = "source", 
                 repos = "http://Rdatatable.github.io/data.table")

## gh pkgs ====================================================================

library("devtools")
install_github("bokeh/rbokeh")
install_github("daattali/shinyjs")
install_github("dgrtwo/gganimate")
install_github("dkahle/ggmap")
install_github("ellisp/forecastHybrid/pkg")
install_github("fstPackage/fst", ref = "develop")
install_github("hadley/assertthat")
install_github("hadley/devtools")
install_github("hadley/multidplyr")
install_github("hadley/dtplyr")
install_github("hadley/pryr")
install_github("hadley/purrrlyr")
install_github("hadley/readr")
install_github("hadley/reshape")
install_github("hadley/rvest")
install_github("hadley/scales")
install_github("hadley/testthat")
install_github("hrbrmstr/ggalt")
install_github("hrbrmstr/hrbrthemes")
install_github("jimhester/lintr")
install_github("jkrijthe/Rtsne")
install_github("juliasilge/tidytext")
install_github("klutometis/roxygen")
install_github("lme4/lme4", dependencies=TRUE)
install_github("ramnathv/rCharts")
install_github("ramnathv/slidify")
install_github(c("ramnathv/htmlwidgets", "rstudio/dygraphs"))
install_github("rich-iannone/DiagrammeR")
install_github("r-lib/httr")
install_github("rmcelreath/rethinking")
install_github("robjhyndman/forecast")
install_github("ropensci/plotly")
install_github("rstudio/blogdown")
install_github("rstudio/DT")
install_github("rstudio/ggvis")
install_github("rstudio/leaflet")
install_github("rstudio/revealjs")
install_github("rstudio/reticulate")
install_github("rstudio/rmarkdown")
install_github("rstudio/shiny")
install_github("rstudio/flexdashboard")
install_github("rstudio/shinydashboard")
install_github("rstudio/sparklyr")
install_github("rstudio/tensorflow")
install_github("sinhrks/ggfortify")
install_github("slowkow/ggrepel")
install_github("stan-dev/rstanarm", args = "--preclean", build_vignettes = FALSE)
install_github("tidyverse/broom")
install_github("tidyverse/dplyr")
install_github("tidyverse/dbplyr")
install_github("tidyverse/forcats")
install_github("tidyverse/glue")
install_github("tidyverse/ggplot2")
install_github("tidyverse/lubridate")
install_github("tidyverse/magrittr")
install_github("tidyverse/modelr")
install_github("tidyverse/purrr")
install_github("tidyverse/readr")
install_github("tidyverse/readxl")
install_github("tidyverse/reprex")
install_github("tidyverse/rlang")
install_github("tidyverse/stringr")
install_github("tidyverse/tidyr")
install_github("tidyverse/tibble")
install_github("tidyverse/tidyverse")
install_github("tidyverse/tidyverse")
install_github('topepo/caret/pkg/caret')
install_github("wesm/feather/R")
install_github('wch/R6', build_vignettes = FALSE)
install_github("yihui/animation")
install_github("yihui/knitr")
install_github("yihui/xaringan")
